# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: descoberta.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='descoberta.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x64\x65scoberta.proto\"\xb7\x01\n\x12MensagemDescoberta\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12\x33\n\x0b\x64\x65vice_type\x18\x03 \x01(\x0e\x32\x1e.MensagemDescoberta.DeviceType\x12\x12\n\nip_address\x18\x04 \x01(\t\x12\x0c\n\x04port\x18\x05 \x01(\x05\"7\n\nDeviceType\x12\x0f\n\x0btemperatura\x10\x00\x12\x0b\n\x07umidade\x10\x01\x12\x0b\n\x07\x61tuador\x10\x02\x62\x06proto3')
)



_MENSAGEMDESCOBERTA_DEVICETYPE = _descriptor.EnumDescriptor(
  name='DeviceType',
  full_name='MensagemDescoberta.DeviceType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='temperatura', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='umidade', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='atuador', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=149,
  serialized_end=204,
)
_sym_db.RegisterEnumDescriptor(_MENSAGEMDESCOBERTA_DEVICETYPE)


_MENSAGEMDESCOBERTA = _descriptor.Descriptor(
  name='MensagemDescoberta',
  full_name='MensagemDescoberta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_id', full_name='MensagemDescoberta.device_id', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_type', full_name='MensagemDescoberta.device_type', index=1,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip_address', full_name='MensagemDescoberta.ip_address', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='MensagemDescoberta.port', index=3,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MENSAGEMDESCOBERTA_DEVICETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=204,
)

_MENSAGEMDESCOBERTA.fields_by_name['device_type'].enum_type = _MENSAGEMDESCOBERTA_DEVICETYPE
_MENSAGEMDESCOBERTA_DEVICETYPE.containing_type = _MENSAGEMDESCOBERTA
DESCRIPTOR.message_types_by_name['MensagemDescoberta'] = _MENSAGEMDESCOBERTA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MensagemDescoberta = _reflection.GeneratedProtocolMessageType('MensagemDescoberta', (_message.Message,), dict(
  DESCRIPTOR = _MENSAGEMDESCOBERTA,
  __module__ = 'descoberta_pb2'
  # @@protoc_insertion_point(class_scope:MensagemDescoberta)
  ))
_sym_db.RegisterMessage(MensagemDescoberta)


# @@protoc_insertion_point(module_scope)
