/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8-dev */

#ifndef PB_PROTO_MENSAGENS_PB_H_INCLUDED
#define PB_PROTO_MENSAGENS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Discovery {
    char message[101];
} Discovery;

typedef struct _Identification {
    char device_type[61];
    char device_ip[21];
    int32_t device_port;
    char protocol[6];
} Identification;

typedef struct _GatewayPort {
    int32_t gateway_port;
} GatewayPort;

typedef struct _GatewayToDeviceMessage {
    char command[101];
} GatewayToDeviceMessage;

typedef struct _DeviceToGatewayMessage {
    char response[101];
} DeviceToGatewayMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Discovery_init_default                   {""}
#define Identification_init_default              {"", "", 0, ""}
#define GatewayPort_init_default                 {0}
#define GatewayToDeviceMessage_init_default      {""}
#define DeviceToGatewayMessage_init_default      {""}
#define Discovery_init_zero                      {""}
#define Identification_init_zero                 {"", "", 0, ""}
#define GatewayPort_init_zero                    {0}
#define GatewayToDeviceMessage_init_zero         {""}
#define DeviceToGatewayMessage_init_zero         {""}

/* Field tags (for use in manual encoding/decoding) */
#define Discovery_message_tag                    1
#define Identification_device_type_tag           1
#define Identification_device_ip_tag             2
#define Identification_device_port_tag           3
#define Identification_protocol_tag              4
#define GatewayPort_gateway_port_tag             1
#define GatewayToDeviceMessage_command_tag       1
#define DeviceToGatewayMessage_response_tag      1

/* Struct field encoding specification for nanopb */
#define Discovery_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   message,           1)
#define Discovery_CALLBACK NULL
#define Discovery_DEFAULT NULL

#define Identification_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   device_type,       1) \
X(a, STATIC,   SINGULAR, STRING,   device_ip,         2) \
X(a, STATIC,   SINGULAR, INT32,    device_port,       3) \
X(a, STATIC,   SINGULAR, STRING,   protocol,          4)
#define Identification_CALLBACK NULL
#define Identification_DEFAULT NULL

#define GatewayPort_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    gateway_port,      1)
#define GatewayPort_CALLBACK NULL
#define GatewayPort_DEFAULT NULL

#define GatewayToDeviceMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   command,           1)
#define GatewayToDeviceMessage_CALLBACK NULL
#define GatewayToDeviceMessage_DEFAULT NULL

#define DeviceToGatewayMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   response,          1)
#define DeviceToGatewayMessage_CALLBACK NULL
#define DeviceToGatewayMessage_DEFAULT NULL

extern const pb_msgdesc_t Discovery_msg;
extern const pb_msgdesc_t Identification_msg;
extern const pb_msgdesc_t GatewayPort_msg;
extern const pb_msgdesc_t GatewayToDeviceMessage_msg;
extern const pb_msgdesc_t DeviceToGatewayMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Discovery_fields &Discovery_msg
#define Identification_fields &Identification_msg
#define GatewayPort_fields &GatewayPort_msg
#define GatewayToDeviceMessage_fields &GatewayToDeviceMessage_msg
#define DeviceToGatewayMessage_fields &DeviceToGatewayMessage_msg

/* Maximum encoded size of messages (where known) */
#define DeviceToGatewayMessage_size              102
#define Discovery_size                           102
#define GatewayPort_size                         11
#define GatewayToDeviceMessage_size              102
#define Identification_size                      102
#define PROTO_MENSAGENS_PB_H_MAX_SIZE            Discovery_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
