/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "proto_mensagens.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Discovery, Discovery, AUTO)


PB_BIND(Identification, Identification, AUTO)


PB_BIND(GatewayPort, GatewayPort, AUTO)


PB_BIND(GatewayToDeviceMessage, GatewayToDeviceMessage, AUTO)


PB_BIND(DeviceToGatewayMessage, DeviceToGatewayMessage, AUTO)



